name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v5
